# -*- coding: utf-8 -*-
"""phase1_asr_ctc_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHuqZLsptahwIXrSUbFURB7ueJzNoCfn

# Phase 1 — ASR Head Training v2 (cached mHuBERT features + CTC)

Emergency Call Intelligence System — PoC

**Design:** because the backbone is fully frozen, the mHuBERT-147 outputs are computed **once** and written to disk (Stage A). Training (Stage B) only fits the 768->30 linear CTC head over that cache, so 30 epochs take minutes on a GPU.

**Requirements:** about 24 GB VRAM (8 GB is enough for Stage A), about 40 GB RAM and **about 30 GB of free disk** (feature cache: train about 27 GB plus dev about 0.8 GB, float16).

**Usage:**
1. Set `MAX_TRAIN_SAMPLES` in the config cell (`512` for a quick smoke test, `None` for the real run).
2. Run All. Stage A skips itself when the cache exists, so restarting after an interruption is safe (a half-finished cache is deleted, a complete one is left alone).
3. Watch the epoch time and dev WER in the `[TRAIN]` lines. The best model is saved to `OUTPUT_DIR`.
"""

# 1. Dependencies, once per fresh runtime
!pip install -q "transformers>=4.44" "datasets>=2.20" jiwer torchaudio soundfile

# 2. Import & config
import os, json, time, math, itertools, statistics
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Sampler

from datasets import load_dataset, Audio
from transformers import Wav2Vec2CTCTokenizer, Wav2Vec2FeatureExtractor, HubertModel
import jiwer

# ================= CONFIG =================
BACKBONE_ID       = "utter-project/mHuBERT-147"
DATASET_ID        = "openslr/librispeech_asr"
SR                = 16_000
HID               = 768                  # mHuBERT-base hidden dim

CACHE_DIR         = "./feat_cache"       # ~30 GB (full run)
OUTPUT_DIR        = "./phase1_ctc_head"

MAX_TRAIN_SAMPLES = None                 # 512 = smoke test, None = full train-clean-100
MAX_EVAL_SAMPLES  = None                 # None means all of dev-clean (2703 samples)

PRECOMPUTE_BATCH  = 12                   # Stage A forward batch (utterances)
TRAIN_BATCH       = 256                   # Stage B batch (over the cache, comfortable)
NUM_EPOCHS        = 30
LR                = 2e-3
LR_PATIENCE       = 2                    # ReduceLROnPlateau (dev-WER)
LR_FACTOR         = 0.5
STOP_PATIENCE     = 4                    # early stopping (dev-WER)
NUM_WORKERS       = 2                    # shared Xeon, 2 is enough

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"[ENV] torch={torch.__version__} device={DEVICE}"
      + (f" gpu={torch.cuda.get_device_name(0)}" if DEVICE == "cuda" else ""))

# 3. Vocab & tokenizer (30 tokens: 27 characters + | + [UNK] + [PAD]=blank)
chars = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ'")
vocab = {c: i for i, c in enumerate(chars)}
vocab["|"]     = len(vocab)   # word separator (space)
vocab["[UNK]"] = len(vocab)
vocab["[PAD]"] = len(vocab)   # CTC blank
with open("vocab.json", "w") as f:
    json.dump(vocab, f)

tokenizer = Wav2Vec2CTCTokenizer("vocab.json", unk_token="[UNK]",
                                 pad_token="[PAD]", word_delimiter_token="|")
feature_extractor = Wav2Vec2FeatureExtractor(
    feature_size=1, sampling_rate=SR, padding_value=0.0,
    do_normalize=True, return_attention_mask=True)

VOCAB_SIZE = len(vocab)
BLANK_ID   = vocab["[PAD]"]
ID2CH      = {i: c for c, i in vocab.items()}
print(f"[VOCAB] {VOCAB_SIZE} token, blank={BLANK_ID}")

# 4. STAGE A - compute the mHuBERT outputs once and write them to disk
# Format: <tag>.f16 holds consecutive [T_i x 768] float16 blocks, <tag>.json holds lengths, labels and text.
def precompute_split(backbone, split, tag, max_samples=None):
    feat_path = os.path.join(CACHE_DIR, f"{tag}.f16")
    meta_path = os.path.join(CACHE_DIR, f"{tag}.json")
    if os.path.exists(meta_path):
        print(f"[CACHE] {tag}: ready, skipping")
        return
    if os.path.exists(feat_path):
        os.remove(feat_path)  # a half-finished earlier attempt

    stream = load_dataset(DATASET_ID, "clean", split=split, streaming=True)
    stream = stream.cast_column("audio", Audio(sampling_rate=SR))
    it = itertools.islice(stream, max_samples) if max_samples else iter(stream)

    lengths, labels, texts = [], [], []
    t0, done, sec_audio = time.perf_counter(), 0, 0.0
    fout = open(feat_path, "ab")

    def flush(buf_audio, buf_text):
        nonlocal done, sec_audio
        enc = feature_extractor(buf_audio, sampling_rate=SR, padding=True,
                                return_tensors="pt", return_attention_mask=True)
        iv = enc.input_values.to(DEVICE, dtype=torch.float16)
        am = enc.attention_mask.to(DEVICE)
        with torch.no_grad():
            hs = backbone(iv, attention_mask=am).last_hidden_state  # [B,T,768] fp16
        valid = backbone._get_feat_extract_output_lengths(am.sum(-1)).tolist()
        hs = hs.cpu().numpy()
        for i, (T, txt) in enumerate(zip(valid, buf_text)):
            hs[i, :T].astype(np.float16).tofile(fout)
            lengths.append(int(T))
            labels.append(tokenizer(txt.upper()).input_ids)
            texts.append(txt.upper())
            done += 1
            sec_audio += len(buf_audio[i]) / SR
        if done % 240 < len(buf_audio):
            el = time.perf_counter() - t0
            print(f"[PRE] {tag}: {done} samples | {sec_audio/3600:.2f} hours of audio | "
                  f"{sec_audio/max(el,1e-9):.0f}x real time")

    buf_a, buf_t = [], []
    for ex in it:
        buf_a.append(ex["audio"]["array"].astype(np.float32))
        buf_t.append(ex["text"])
        if len(buf_a) == PRECOMPUTE_BATCH:
            flush(buf_a, buf_t); buf_a, buf_t = [], []
    if buf_a:
        flush(buf_a, buf_t)
    fout.close()

    with open(meta_path, "w") as f:
        json.dump({"lengths": lengths, "labels": labels, "texts": texts, "dim": HID}, f)
    gb = os.path.getsize(feat_path) / 1e9
    print(f"[PRE] {tag}: done - {len(lengths)} samples, {gb:.1f} GB, "
          f"{(time.perf_counter()-t0)/60:.1f} min")


os.makedirs(CACHE_DIR, exist_ok=True)
need = [t for t in ("train", "dev")
        if not os.path.exists(os.path.join(CACHE_DIR, f"{t}.json"))]
if need:
    print(f"[PRE] loading the backbone ({BACKBONE_ID}, fp16)...")
    backbone = HubertModel.from_pretrained(
        BACKBONE_ID, torch_dtype=torch.float16).to(DEVICE).eval()
    if "train" in need:
        precompute_split(backbone, "train.100", "train", MAX_TRAIN_SAMPLES)
    if "dev" in need:
        precompute_split(backbone, "validation", "dev", MAX_EVAL_SAMPLES)
    del backbone
    if DEVICE == "cuda":
        torch.cuda.empty_cache()
else:
    print("[PRE] the whole cache is ready")

# 5. Dataset over the cache, length-bucketed batch sampler and collate
class FeatDataset(Dataset):
    def __init__(self, tag):
        with open(os.path.join(CACHE_DIR, f"{tag}.json")) as f:
            meta = json.load(f)
        self.lengths = meta["lengths"]
        self.labels  = meta["labels"]
        self.texts   = meta["texts"]
        self.offsets = np.concatenate([[0], np.cumsum(self.lengths)])[:-1]
        self.mm = np.memmap(os.path.join(CACHE_DIR, f"{tag}.f16"),
                            dtype=np.float16, mode="r").reshape(-1, HID)

    def __len__(self):
        return len(self.lengths)

    def __getitem__(self, i):
        o, L = int(self.offsets[i]), self.lengths[i]
        x = torch.from_numpy(np.array(self.mm[o:o+L]))
        return x, torch.tensor(self.labels[i], dtype=torch.long), L, i


class BucketBatchSampler(Sampler):
    """Sort by length, split into batches, shuffle the batch order, so padding stays low."""
    def __init__(self, lengths, batch_size, shuffle=True):
        order = np.argsort(lengths)
        self.batches = [order[i:i+batch_size].tolist()
                        for i in range(0, len(order), batch_size)]
        self.shuffle = shuffle

    def __iter__(self):
        idx = np.random.permutation(len(self.batches)) if self.shuffle \
              else range(len(self.batches))
        for b in idx:
            yield self.batches[b]

    def __len__(self):
        return len(self.batches)


def collate(items):
    feats, labs, lens, idxs = zip(*items)
    B, Tmax = len(feats), max(lens)
    Smax = max(len(l) for l in labs)
    x = torch.zeros(B, Tmax, HID)
    y = torch.full((B, Smax), BLANK_ID, dtype=torch.long)
    for i, (f, l) in enumerate(zip(feats, labs)):
        x[i, :f.shape[0]] = f
        y[i, :len(l)] = l
    return (x, y, torch.tensor(lens, dtype=torch.long),
            torch.tensor([len(l) for l in labs], dtype=torch.long),
            list(idxs))


train_ds = FeatDataset("train")
dev_ds   = FeatDataset("dev")
train_dl = DataLoader(train_ds, batch_sampler=BucketBatchSampler(train_ds.lengths, TRAIN_BATCH),
                      collate_fn=collate, num_workers=NUM_WORKERS, pin_memory=(DEVICE=="cuda"))
dev_dl   = DataLoader(dev_ds, batch_sampler=BucketBatchSampler(dev_ds.lengths, TRAIN_BATCH, shuffle=False),
                      collate_fn=collate, num_workers=NUM_WORKERS, pin_memory=(DEVICE=="cuda"))
print(f"[DATA] train={len(train_ds)} dev={len(dev_ds)} | "
      f"{len(train_dl)} train batch/epoch")

# 6. Model (linear CTC head), greedy decode, WER
class CTCHead(nn.Module):
    def __init__(self, dim=HID, vocab_size=VOCAB_SIZE, p_drop=0.1):
        super().__init__()
        self.dropout = nn.Dropout(p_drop)
        self.fc = nn.Linear(dim, vocab_size)

    def forward(self, x):                 # [B,T,768] -> [B,T,V]
        return self.fc(self.dropout(x))


def greedy_decode(ids):
    out, prev = [], -1
    for t in ids:
        if t != prev and t != BLANK_ID:
            out.append(ID2CH.get(t, ""))
        prev = t
    return "".join(out).replace("|", " ").strip()


@torch.no_grad()
def evaluate_wer(model, dl, ds):
    model.eval()
    hyps, refs = [], []
    for x, y, xlen, ylen, idxs in dl:
        logits = model(x.to(DEVICE))
        pred = logits.argmax(-1).cpu().numpy()
        for b, i in enumerate(idxs):
            hyps.append(greedy_decode(pred[b, :xlen[b]].tolist()))
            refs.append(ds.texts[i])
    return jiwer.wer(refs, hyps), hyps, refs

# 7. STAGE B - training loop
model = CTCHead().to(DEVICE)
n_par = sum(p.numel() for p in model.parameters())
print(f"[MODEL] trainable params: {n_par:,} (CTC head only)")

optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", factor=LR_FACTOR, patience=LR_PATIENCE)
ctc = nn.CTCLoss(blank=BLANK_ID, reduction="mean", zero_infinity=True)

os.makedirs(OUTPUT_DIR, exist_ok=True)
best_wer, best_epoch = float("inf"), -1

for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    t0, tot_loss, n_batches = time.perf_counter(), 0.0, 0
    for x, y, xlen, ylen, _ in train_dl:
        x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE)
        logits = model(x)
        logp = logits.log_softmax(-1).transpose(0, 1)      # [T,B,V]
        loss = ctc(logp, y, xlen.to(DEVICE), ylen.to(DEVICE))
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        tot_loss += loss.item(); n_batches += 1

    wer, hyps, refs = evaluate_wer(model, dev_dl, dev_ds)
    scheduler.step(wer)
    lr_now = optimizer.param_groups[0]["lr"]
    print(f"[TRAIN] epoch {epoch:>2} | loss {tot_loss/max(n_batches,1):.4f} | "
          f"dev-WER {wer*100:.2f}% | lr {lr_now:.2e} | "
          f"{time.perf_counter()-t0:.1f} s")

    if wer < best_wer:
        best_wer, best_epoch = wer, epoch
        torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, "ctc_head_best.pt"))
    elif epoch - best_epoch >= STOP_PATIENCE:
        print(f"[TRAIN] early stop (no improvement for {STOP_PATIENCE} epochs)")
        break

tokenizer.save_pretrained(OUTPUT_DIR)
feature_extractor.save_pretrained(OUTPUT_DIR)
print(f"\n[TRAIN] best dev-WER: {best_wer*100:.2f}% (epoch {best_epoch})")
print(f"[TRAIN] head + tokenizer + feature_extractor -> {OUTPUT_DIR}")
print("[TRAIN] sample output:")
for h, r in zip(hyps[:3], refs[:3]):
    print(f"  REF: {r}\n  HYP: {h}")

# 8. (Optional) test-clean evaluation. Roadmap target is WER below 10%
RUN_TEST_EVAL = False   # set to True and run the cell (about 1.4 GB of extra cache)

if RUN_TEST_EVAL:
    if not os.path.exists(os.path.join(CACHE_DIR, "test.json")):
        backbone = HubertModel.from_pretrained(
            BACKBONE_ID, torch_dtype=torch.float16).to(DEVICE).eval()
        precompute_split(backbone, "test.clean", "test", None)
        del backbone
        if DEVICE == "cuda":
            torch.cuda.empty_cache()
    test_ds = FeatDataset("test")
    test_dl = DataLoader(test_ds,
                         batch_sampler=BucketBatchSampler(test_ds.lengths, TRAIN_BATCH, shuffle=False),
                         collate_fn=collate, num_workers=NUM_WORKERS,
                         pin_memory=(DEVICE=="cuda"))
    model.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, "ctc_head_best.pt"),
                                     map_location=DEVICE))
    test_wer, _, _ = evaluate_wer(model, test_dl, test_ds)
    print(f"[TEST] test-clean WER: {test_wer*100:.2f}%  (target < 10%)")

"""### Notes

- **Stage A is a one-off cost.** On an L4 with 24 GB the fp16 forward runs at roughly 100-200x real time, so 100 hours of audio takes about 40-60 minutes. If it is interrupted, Run All again is safe because a completed cache is skipped.
- **Stage B is very cheap.** For a 23K-parameter head an epoch takes seconds to tens of seconds, and all 30 epochs take minutes. The bottleneck is now the memmap disk read, and with 40 GB of RAM the OS page cache holds most of the train cache, so it speeds up from the second epoch on.
- **The inference chain:** audio -> feature_extractor -> mHuBERT (fp16, frozen) -> `ctc_head_best.pt` -> greedy decode. The forward inside `flush` in Stage A plus `greedy_decode` in cell 6 are exactly this chain.
- **Smoke test:** `MAX_TRAIN_SAMPLES=512` and `MAX_EVAL_SAMPLES=256` run end to end in about 5 minutes. Then delete the cache folder (`!rm -rf feat_cache`) and switch to the real run with `None`.
- A WER below 10% with a purely linear head is an aggressive target. If convergence stalls, adding one hidden layer to `CTCHead` (768->768 GELU->30) gives a clear gain for a small departure from the roadmap.
"""

# === LAYER SWEEP: which mHuBERT layer gives the best linear probe? ===
SWEEP_DIR    = "./sweep_cache"
SWEEP_LAYERS = [3, 5, 7, 9, 11, 12]   # hidden_states index (0=embedding, 12=last layer)
N_TRAIN_SW   = 768
N_DEV_SW     = 256
EPOCHS_SW    = 10
BATCH_SW     = 128
LR_SW        = 2e-3

os.makedirs(SWEEP_DIR, exist_ok=True)

def sweep_precompute(backbone, split, n, prefix):
    files = {L: open(os.path.join(SWEEP_DIR, f"{prefix}_L{L}.f16"), "wb")
             for L in SWEEP_LAYERS}
    lengths, labels, texts = [], [], []
    stream = load_dataset(DATASET_ID, "clean", split=split, streaming=True)
    stream = stream.cast_column("audio", Audio(sampling_rate=SR))

    def flush(buf_a, buf_t):
        enc = feature_extractor(buf_a, sampling_rate=SR, padding=True,
                                return_tensors="pt", return_attention_mask=True)
        iv = enc.input_values.to(DEVICE, dtype=torch.float16)
        am = enc.attention_mask.to(DEVICE)
        with torch.no_grad():
            hs = backbone(iv, attention_mask=am,
                          output_hidden_states=True).hidden_states
        valid = backbone._get_feat_extract_output_lengths(am.sum(-1)).tolist()
        for L in SWEEP_LAYERS:
            h = hs[L].cpu().numpy()
            for i, T in enumerate(valid):
                h[i, :T].astype(np.float16).tofile(files[L])
        for T, txt in zip(valid, buf_t):
            lengths.append(int(T))
            labels.append(tokenizer(txt.upper()).input_ids)
            texts.append(txt.upper())

    buf_a, buf_t = [], []
    for ex in itertools.islice(stream, n):
        buf_a.append(ex["audio"]["array"].astype(np.float32))
        buf_t.append(ex["text"])
        if len(buf_a) == PRECOMPUTE_BATCH:
            flush(buf_a, buf_t); buf_a, buf_t = [], []
    if buf_a:
        flush(buf_a, buf_t)
    for f in files.values():
        f.close()
    print(f"[SWEEP] {prefix}: {len(lengths)} samples, {len(SWEEP_LAYERS)} layers")
    return {"lengths": lengths, "labels": labels, "texts": texts}


class SweepDS(Dataset):
    def __init__(self, path, meta):
        self.lengths, self.labels, self.texts = \
            meta["lengths"], meta["labels"], meta["texts"]
        self.offsets = np.concatenate([[0], np.cumsum(self.lengths)])[:-1]
        self.mm = np.memmap(path, dtype=np.float16, mode="r").reshape(-1, HID)
    def __len__(self): return len(self.lengths)
    def __getitem__(self, i):
        o, L = int(self.offsets[i]), self.lengths[i]
        x = torch.from_numpy(np.array(self.mm[o:o+L], dtype=np.float32))
        return x, torch.tensor(self.labels[i], dtype=torch.long), L, i


print("[SWEEP] loading the backbone...")
bb = HubertModel.from_pretrained(BACKBONE_ID, torch_dtype=torch.float16).to(DEVICE).eval()
tr_meta = sweep_precompute(bb, "train.100", N_TRAIN_SW, "tr")
dv_meta = sweep_precompute(bb, "validation", N_DEV_SW, "dv")
del bb
if DEVICE == "cuda": torch.cuda.empty_cache()

ctc_sw = nn.CTCLoss(blank=BLANK_ID, reduction="mean", zero_infinity=True)
results = []
for L in SWEEP_LAYERS:
    tr_ds = SweepDS(os.path.join(SWEEP_DIR, f"tr_L{L}.f16"), tr_meta)
    dv_ds = SweepDS(os.path.join(SWEEP_DIR, f"dv_L{L}.f16"), dv_meta)
    tr_dl = DataLoader(tr_ds, batch_sampler=BucketBatchSampler(tr_ds.lengths, BATCH_SW),
                       collate_fn=collate, num_workers=0)
    dv_dl = DataLoader(dv_ds, batch_sampler=BucketBatchSampler(dv_ds.lengths, BATCH_SW, shuffle=False),
                       collate_fn=collate, num_workers=0)
    probe = CTCHead().to(DEVICE)
    opt = torch.optim.AdamW(probe.parameters(), lr=LR_SW)
    for ep in range(EPOCHS_SW):
        probe.train()
        for x, y, xl, yl, _ in tr_dl:
            logp = probe(x.to(DEVICE)).log_softmax(-1).transpose(0, 1)
            loss = ctc_sw(logp, y.to(DEVICE), xl.to(DEVICE), yl.to(DEVICE))
            opt.zero_grad(set_to_none=True); loss.backward(); opt.step()
    # dev loss + dev WER
    probe.eval(); dl_sum, nb = 0.0, 0
    with torch.no_grad():
        for x, y, xl, yl, _ in dv_dl:
            logp = probe(x.to(DEVICE)).log_softmax(-1).transpose(0, 1)
            dl_sum += ctc_sw(logp, y.to(DEVICE), xl.to(DEVICE), yl.to(DEVICE)).item(); nb += 1
    wer, _, _ = evaluate_wer(probe, dv_dl, dv_ds)
    results.append((L, dl_sum / nb, wer))
    print(f"[SWEEP] layer {L:>2} | dev-loss {dl_sum/nb:.3f} | dev-WER {wer*100:6.2f}%")

print("\n[SWEEP] ===== RANKING (by dev loss) =====")
for L, dl_, w in sorted(results, key=lambda r: r[1]):
    print(f"  layer {L:>2}: dev-loss {dl_:.3f} | dev-WER {w*100:6.2f}%")