# -*- coding: utf-8 -*-
"""phase1_weighted_sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRwThuweFXRODkBx7ynzV7zgYzfGlR93

# Phase 1 fine-tune: **Weighted-Sum** (layers 8-9-10 · int8 · RAM) — "1-99"

After the diagnosis that layer 9 alone is limiting, this **enriches** the feature with a **learnable weighted sum** of layers 8, 9 and 10. The probing peak sits in that band, and 11 was dropped because it drifts toward the pretraining objective and is weak for ASR.

**The "1-99" method:** the backbone runs **once** and the features are written to **RAM** as **per-channel int8** (about 44 GB). There is **no disk feature cache**. Epochs 2 to 100 read from RAM without touching the disk, so steady state is a matter of seconds.

- Only the **model output** is written to disk (`/content/drive/MyDrive/CLEAR/phase1_ws`).
- **RAM budget:** about 40 GB for train plus about 4 GB for dev, in int8. An L4 high-mem instance (about 50 GB) is **right at the edge**. On OOM, cut `WS_LAYERS` down to `[9,10]` or limit `MAX_TRAIN_SAMPLES`.

Baseline reference: **val-CER 8.2%**.

## 1. Drive and dependencies
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q "transformers>=4.44" "datasets>=2.20" jiwer torchaudio soundfile

"""## 2. Import & config
`WS_LAYERS` is the set of layers entering the weighted sum. The paths are kept separate from the baseline and from Phase 2.
"""

import os, json, time, gc
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Sampler
from datasets import load_dataset, Audio
from transformers import Wav2Vec2CTCTokenizer, Wav2Vec2FeatureExtractor, HubertModel
import jiwer

# ================= CONFIG =================
BACKBONE_ID   = "utter-project/mHuBERT-147"
DATASET_ID    = "openslr/librispeech_asr"
SR            = 16_000
HID           = 768

# --- WEIGHTED-SUM (3 layers · int8 · RAM-resident) ---
WS_LAYERS     = [6, 7, 8, 9, 10, 11, 12]        # probing peak is 8-10; 11 (pretraining objective) was dropped
N_WS          = len(WS_LAYERS)

# --- PATHS (model output ONLY, features are NEVER written to disk) ---
OUTPUT_DIR    = "/content/drive/MyDrive/CLEAR/phase1_ws_"

MAX_TRAIN_SAMPLES = None
MAX_EVAL_SAMPLES  = None

TRAIN_BATCH       = 512
NUM_EPOCHS        = 100
LR                = 2e-3
LR_PATIENCE       = 4
LR_FACTOR         = 0.5
STOP_PATIENCE     = 12            # early stopping
NUM_WORKERS       = 0             # the features live in RAM, no I/O, so workers are pointless (and no COW risk)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"[ENV] torch={torch.__version__} device={DEVICE}"
      + (f" gpu={torch.cuda.get_device_name(0)}" if DEVICE == "cuda" else ""))
os.makedirs(OUTPUT_DIR, exist_ok=True)

"""## 3. Vocab and tokenizer (byte-for-byte identical to the baseline)"""

chars = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ'")
vocab = {c: i for i, c in enumerate(chars)}
vocab["|"]     = len(vocab)
vocab["[UNK]"] = len(vocab)
vocab["[PAD]"] = len(vocab)
with open("vocab.json", "w") as f:
    json.dump(vocab, f)
tokenizer = Wav2Vec2CTCTokenizer("vocab.json", unk_token="[UNK]",
                                 pad_token="[PAD]", word_delimiter_token="|")
feature_extractor = Wav2Vec2FeatureExtractor(
    feature_size=1, sampling_rate=SR, padding_value=0.0,
    do_normalize=True, return_attention_mask=True)
VOCAB_SIZE = len(vocab)
BLANK_ID   = vocab["[PAD]"]
UNK_ID     = vocab["[UNK]"]
ID2CH      = {i: c for c, i in vocab.items()}
print(f"[VOCAB] {VOCAB_SIZE} token, blank={BLANK_ID}")

"""## 4. "1-99" precompute — backbone 1×, per-channel int8, into RAM
The backbone processes all the data once. `hidden_states[8,9,10]` are stacked, quantised to int8 with a **per-channel scale** derived from a small calibration set, and kept in RAM. Nothing is written to disk.
"""

# ============================================================
# The "1-99" method: the backbone runs ONCE and the features are written to RAM as int8.
# Epochs 2-100 read from RAM without touching the disk -> steady state in seconds.
# Per-channel int8 quantisation: the [N_WS,768] scale comes from a small calibration set.
# ============================================================

class RawAudioDataset(Dataset):
    def __init__(self, hf_ds, lengths, labels):
        self.ds = hf_ds
        self.lengths = lengths
        self.labels = labels

    def __len__(self): return len(self.ds)

    def __getitem__(self, i):
        # pulls the raw audio from the HF Dataset only on demand
        audio_array = np.asarray(self.ds[i]["audio"]["array"], dtype=np.float32)
        return torch.from_numpy(audio_array), torch.tensor(self.labels[i], dtype=torch.long), i

def on_the_fly_collate(items):
    audios, labs, idxs = zip(*items)
    B = len(audios)

    # zero-pad the clips to the longest clip in the batch
    x_audio = torch.nn.utils.rnn.pad_sequence(audios, batch_first=True, padding_value=0.0)
    audio_lens = torch.tensor([len(a) for a in audios], dtype=torch.long)

    # pad the texts (the labels)
    Smax = max(len(l) for l in labs)
    y = torch.full((B, Smax), BLANK_ID, dtype=torch.long)
    for i, l in enumerate(labs): y[i, :len(l)] = l

    return x_audio, y, audio_lens, torch.tensor([len(l) for l in labs], dtype=torch.long), list(idxs)

def raw_collate(items):
    return [it[0] for it in items], [it[1] for it in items]

def gpu_normalize(iv, lengths):
    for i in range(iv.shape[0]):
        L = lengths[i]; x = iv[i, :L]
        iv[i, :L] = (x - x.mean()) / torch.sqrt(x.var(unbiased=False) + 1e-5)
    return iv

@torch.no_grad()
def _forward_batch(backbone, buf_audio):
    Ls = [len(a) for a in buf_audio]; Tmax = max(Ls)
    batch = np.zeros((len(buf_audio), Tmax), dtype=np.float32)
    for i, a in enumerate(buf_audio): batch[i, :len(a)] = a
    iv = torch.from_numpy(batch).pin_memory().to(DEVICE, non_blocking=True)
    iv = gpu_normalize(iv, Ls).to(torch.float16)
    am = torch.zeros((len(buf_audio), Tmax), dtype=torch.long, device=DEVICE)
    for i, L in enumerate(Ls): am[i, :L] = 1
    out = backbone(iv, attention_mask=am, output_hidden_states=True)
    hs = torch.stack([out.hidden_states[L] for L in WS_LAYERS], dim=1)   # [B,N_WS,T,768] fp16
    valid = backbone._get_feat_extract_output_lengths(am.sum(-1)).tolist()
    return hs.float().cpu().numpy(), [int(v) for v in valid]

def _load_split(split, max_samples):
    if split == "train.100":
        hf = load_dataset(DATASET_ID, data_files={"train": "clean/train.100/*.parquet"},
                          split="train", verification_mode="no_checks")
    else:
        hf = load_dataset(DATASET_ID, data_files={"validation": "clean/validation/*.parquet"},
                          split="validation", verification_mode="no_checks")
    hf = hf.cast_column("audio", Audio(sampling_rate=SR))
    if max_samples: hf = hf.select(range(min(max_samples, len(hf))))
    return hf

@torch.no_grad()
def build_ram_cache(backbone, split, tag, scale=None, max_samples=None):
    hf = _load_split(split, max_samples)
    # sort by length, which cuts the padding waste in the backbone batches
    raw_lens = [len(hf[i]["audio"]["array"]) for i in range(len(hf))]
    order = sorted(range(len(raw_lens)), key=lambda i: raw_lens[i])
    hf = hf.select(order); raw_lens = [raw_lens[i] for i in order]
    feat_lens = [int(v) for v in
                 backbone._get_feat_extract_output_lengths(torch.tensor(raw_lens)).tolist()]
    total = sum(feat_lens); gb = total * N_WS * HID / 1e9
    print(f"[RAM] {tag}: {len(hf)} samples, {total:,} frames -> allocating {gb:.1f} GB of int8...")
    feats = np.empty((total, N_WS, HID), dtype=np.int8)      # << LARGE RAM ALLOC

    loader = DataLoader(RawAudioDataset(hf), batch_size=PRECOMPUTE_BATCH,
                        num_workers=8, collate_fn=raw_collate, prefetch_factor=4)

    # --- 1) CALIBRATION: per-channel abs-max over the first CALIB_N samples -> scale ---
    if scale is None:
        absmax = np.zeros((N_WS, HID), np.float32); seen = 0
        for buf_audio, _ in loader:
            hs, valid = _forward_batch(backbone, buf_audio)
            for i, T in enumerate(valid):
                absmax = np.maximum(absmax, np.abs(hs[i, :, :T, :]).max(axis=1))
                seen += 1
            if seen >= CALIB_N: break
        scale = (absmax / 127.0); scale[scale < 1e-8] = 1e-8
        print(f"[RAM] {tag}: scale ready (per-channel, {seen} samples), median={np.median(scale):.4g}")

    # --- 2) MAIN PASS: quantise all the data to int8 and write it to RAM ---
    labels, texts = [], []
    wp, done, t0 = 0, 0, time.perf_counter()
    for buf_audio, buf_text in loader:
        hs, valid = _forward_batch(backbone, buf_audio)
        for i, (T, txt) in enumerate(zip(valid, buf_text)):
            block = hs[i, :, :T, :].transpose(1, 0, 2)                    # [T,N_WS,768]
            feats[wp:wp+T] = np.clip(np.round(block / scale), -127, 127).astype(np.int8)
            wp += T
            labels.append(tokenizer(txt).input_ids); texts.append(txt); done += 1
        if done % 2000 < PRECOMPUTE_BATCH:
            print(f"[RAM] {tag}: {done}/{len(hf)} | {done/(time.perf_counter()-t0):.0f} samples/s")
    assert wp == total, (wp, total)
    offsets = np.concatenate([[0], np.cumsum(feat_lens)])[:-1].astype(np.int64)
    print(f"[RAM] {tag}: done - {done} samples, {gb:.1f} GB, {(time.perf_counter()-t0)/60:.1f} min")
    return {"feats": feats, "offsets": offsets, "lengths": feat_lens,
            "labels": labels, "texts": texts}, scale

# --- SECTION 5: on-the-fly Dataset and collate ---
class OnTheFlyDataset(Dataset):
    def __init__(self, hf_ds):
        self.ds = hf_ds

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, i):
        ex = self.ds[i]
        # fetch the raw audio as a numpy array and build the label
        audio_array = np.asarray(ex["audio"]["array"], dtype=np.float32)
        label_ids = tokenizer(ex["text"].upper()).input_ids
        return torch.from_numpy(audio_array), torch.tensor(label_ids, dtype=torch.long), i

def on_the_fly_collate(items):
    audios, labs, idxs = zip(*items)
    B = len(audios)

    # 1. zero-pad the clips to the longest clip in the batch
    x_audio = torch.nn.utils.rnn.pad_sequence(audios, batch_first=True, padding_value=0.0)
    audio_lens = torch.tensor([len(a) for a in audios], dtype=torch.long)

    # 2. pad the labels (the texts) with BLANK_ID
    Smax = max(len(l) for l in labs)
    y = torch.full((B, Smax), BLANK_ID, dtype=torch.long)
    for i, l in enumerate(labs):
        y[i, :len(l)] = l

    return x_audio, y, audio_lens, torch.tensor([len(l) for l in labs], dtype=torch.long), list(idxs)

# build the DataLoaders
train_ds = OnTheFlyDataset(_load_split("train.100", MAX_TRAIN_SAMPLES))
dev_ds   = OnTheFlyDataset(_load_split("validation", MAX_EVAL_SAMPLES))

# NOTE: num_workers > 0 is fine now, since mp3/parquet is read from disk on the fly
train_dl = DataLoader(train_ds, batch_size=TRAIN_BATCH, shuffle=True,
                      collate_fn=on_the_fly_collate, num_workers=4, pin_memory=True)
dev_dl   = DataLoader(dev_ds, batch_size=TRAIN_BATCH, shuffle=False,
                      collate_fn=on_the_fly_collate, num_workers=4, pin_memory=True)

"""## 6. Weighted-Sum head + decode + eval
`layer_w` is 3 learnable weights under a softmax. The int8 features are **dequantised** to fp32 inside the model using the per-channel `scale` buffer. They start out equal and training decides which layer dominates.
"""

# --- SECTION 6: simplified weighted-sum head ---
class WeightedSumHead(nn.Module):
    def __init__(self, n_ws=N_WS, dim=HID, vocab_size=VOCAB_SIZE):
        super().__init__()
        # 7 weights for 7 layers
        self.layer_w = nn.Parameter(torch.zeros(n_ws))
        self.net = nn.Sequential(nn.Linear(dim, dim), nn.ELU(), nn.Linear(dim, vocab_size))

    def forward(self, x):
        # x: [B, T, N_WS, 768], the clean tensor coming out of mHuBERT
        w = self.layer_w.softmax(0)
        feat = (x * w[None, None, :, None]).sum(2)   # [B, T, 768]
        return self.net(feat)

def greedy_decode(ids):
    out, prev = [], -1
    for t in ids:
        if t != prev and t != BLANK_ID and t != UNK_ID:
            out.append(ID2CH.get(t, ""))
        prev = t
    return "".join(out).replace("|", " ").strip()

@torch.no_grad()
def evaluate_wer(model, dl, ds):
    model.eval()
    hyps, refs = [], []
    for x, y, xlen, ylen, idxs in dl:
        logits = model(x.to(DEVICE, non_blocking=True))
        pred = logits.argmax(-1).cpu().numpy()
        for b, i in enumerate(idxs):
            hyps.append(greedy_decode(pred[b, :xlen[b]].tolist()))
            refs.append(ds.texts[i])
    return jiwer.wer(refs, hyps), jiwer.cer(refs, hyps), hyps, refs

"""## 7. Training
Every epoch prints the **layer weights** (`w=[...]`) so you can see which layer became dominant. The best model is saved to Drive and early stopping is enabled.
"""

# --- SECTION 7: on-the-fly training with delta checkpointing ---

# 1. load mHuBERT, move it to the GPU and FREEZE its weights
print(f"[PRE] loading the backbone ({BACKBONE_ID})...")
backbone = HubertModel.from_pretrained(BACKBONE_ID).to(DEVICE).eval()
for param in backbone.parameters():
    param.requires_grad = False  # critical, otherwise you run out of memory

model = WeightedSumHead().to(DEVICE)
optimizer = torch.optim.AdamW(model.parameters(), lr=LR)

# New scheduler: threshold=0.005 (relative)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", factor=LR_FACTOR, patience=LR_PATIENCE,
    threshold=0.005, threshold_mode="rel"
)
ctc = nn.CTCLoss(blank=BLANK_ID, reduction="mean", zero_infinity=True)

best_cer, best_epoch = float("inf"), 0

for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    t0, tot_loss, nb = time.perf_counter(), 0.0, 0

    for x_audio, y, x_audio_lens, ylen, idxs in train_dl:
        x_audio, y = x_audio.to(DEVICE), y.to(DEVICE)

        # --- ON-THE-FLY FEATURE EXTRACTION, with FP16 acceleration ---
        with torch.no_grad():
            with torch.autocast(device_type="cuda", dtype=torch.float16):
                # build the mask
                am = torch.zeros(x_audio.shape, dtype=torch.long, device=DEVICE)
                for i, L in enumerate(x_audio_lens): am[i, :L] = 1

                # feed the audio to mHuBERT
                out = backbone(x_audio, attention_mask=am, output_hidden_states=True)

                # select only the 7 layers we want and stack them
                hs = torch.stack([out.hidden_states[L] for L in WS_LAYERS], dim=2)

                # valid time-step lengths for CTC after the CNN downsampling
                xlen = backbone._get_feat_extract_output_lengths(x_audio_lens.to(DEVICE))

        # --- HEAD TRAINING ---
        logits = model(hs.float()) # cast to fp32 so the loss does not blow up
        logp = logits.log_softmax(-1).transpose(0, 1)
        loss = ctc(logp, y, xlen, ylen.to(DEVICE))

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

        tot_loss += loss.item(); nb += 1

    # end-of-epoch evaluations
    va_wer, va_cer, _, _ = evaluate_wer(model, dev_dl, dev_ds)
    lr_now = optimizer.param_groups[0]["lr"]
    wnow = model.layer_w.softmax(0).detach().cpu().numpy().round(3)

    print(f"epoch {epoch:>3} | loss {tot_loss/nb:.3f} | {time.perf_counter()-t0:.1f}s "
          f"| VAL cer {va_cer*100:.1f}% | lr {lr_now:.1e} | w={wnow}")

    # step the scheduler on val_cer, it applies its own 0.5% rule
    scheduler.step(va_cer)

    # --- NEW DELTA CHECKPOINT LOGIC ---
    min_required_cer = best_cer * (1.0 - 0.005) # a hard 0.5% improvement gate

    if va_cer < min_required_cer:
        best_cer, best_epoch = va_cer, epoch
        torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, "ctc_head_ws.pt"))
        print(f"   [SAVE] new best val-CER {va_cer*100:.2f}% -> {OUTPUT_DIR}/ctc_head_ws.pt")
    elif epoch - best_epoch >= STOP_PATIENCE:
        print(f"[STOP] no improvement above 0.5% for {STOP_PATIENCE} epochs. (best {best_cer*100:.2f}% @ e{best_epoch})")
        break